<?php

$config["games"]["en"] = [
    [
        "name"          => "Mystery of the Theatre",
        "winner_place"  => 2,
        "project"       => "virma",
        "team"          => "21tiko4f",
        "team_name"     => "Rakettiryhmä",
        "description"   => "In Mystery of the Theatre you will try to figure out the story of the legendary ghost.",
        "logo"          => "21tiko4f.webp",
        "website"       => "/21tiko4f/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.Rakettiryhm.TeatterinMysteeri",
        "appstore"      => "https://apps.apple.com/fi/app/teatterinmysteeri/id1623442275",
        "client"        => "Tampere Theatre",
        "client_website"=> "https://tampereenteatteri.fi/the-tampere-theatre/",
    ],
    [
        "name"          => "Rooftop Gardener",
        "project"       => "fusilli",
        "team"          => "21tiko3a",
        "team_name"     => "Team Chili",
        "description"   => "Get ready for fast-paced action protecting your rooftop garden!",
        "logo"          => "21tiko3a.webp",
        "website"       => "https://webpages.tuni.fi/21tiko3a/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.TeamChili.RooftopGardener",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Löylyn Taika",
        "project"       => "virma",
        "team"          => "21tiko2d",
        "team_name"     => "DEE",
        "description"   => "An island, a forest, a lakeside and an elf-in-training. Welcome to the magical sauna! ",
        "logo"          => "21tiko2d.webp",
        "website"       => "/21tiko2d/index-en.html",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.TIKO2D.LylynTaika",
        "client"        => "Saunakonkeli",
        "client_website"=> "https://www.saunakonkeli.com/english",
    ],
    [
        "name"          => "Trash defender",
        "project"       => "ruoko",
        "team"          => "21tiko1a",
        "team_name"     => "NRE",
        "description"   => "Save the world from trash in Trash defender!",
        "logo"          => "21tiko1a.webp",
        "website"       => "/21tiko1a/portaali.html",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.NRE.trash_defender",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Narwala",
        "project"       => "virma",
        "team"          => "21tiko4c",
        "team_name"     => "FragFrog",
        "description"   => "Barn simulator. Keep your henhouse clean, make your henhouse bigger by purchasing more chickens and buy them funny hats!",
        "logo"          => "21tiko4c.webp",
        "website"       => "/21tiko4c/",
        "playstore"     => null,
        "client"        => "Narva Homestead Accommodations",
        "client_website"=> "https://www.narvanmaatilamajoitus.fi/",
    ],
    [
        "name"          => "SupperStar",
        "project"       => "fusilli",
        "team"          => "21tiko3e",
        "team_name"     => null,
        "description"   => "Welcome to SupperStar! Your local neighbourhood restaurant!",
        "logo"          => "21tiko3e.webp",
        "website"       => "/21tiko3e/SupperstarENG.html",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.Tiko3e.SupperStar",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Takeaway Hero",
        "project"       => "ruoko",
        "team"          => "21tiko1e",
        "team_name"     => null,
        "description"   => "Pack the food, sort the trash and don't mix those two up. Not all heroes wear capes. They recycle!",
        "logo"          => "21tiko1e.webp",
        "website"       => "/21tiko1e/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.TIKO1E.TakeawayHero",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Ilola Express",
        "project"       => "virma",
        "team"          => "21tiko4d",
        "team_name"     => "J-A-L-O",
        "description"   => "A farm themed version of the well-known snake game with minor modifications.",
        "logo"          => "21tiko4d.webp",
        "website"       => "/21tiko4d/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.JALO.IlolaExpress",
        "client"        => "Ilola Farm",
        "client_website"=> "https://www.ilolanmaatila.fi/juhlat",
    ],
    [
        "name"          => "Amazing Jump",
        "project"       => "virma",
        "team"          => "21tiko4b",
        "team_name"     => "KoodiÄijät",
        "description"   => "Game is an endless runner where you have to dodge obstacles and not fall from the rooftops.",
        "logo"          => "21tiko4b.webp",
        "website"       => "/21tiko4b/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.Koodiijt.AmazingJump",
        "client"        => "Amazing City",
        "client_website"=> "https://amazingcity.fi/en/home/",
    ],
    [
        "name"          => "Trash Adventure",
        "project"       => "ruoko",
        "team"          => "21tiko1b",
        "team_name"     => null,
        "description"   => "Sort your way through the homes occupied by take-away enemies, and sort your trash!",
        "logo"          => "21tiko1b.webp",
        "website"       => "/21tiko1b/TrashAdventure_EN.html",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.DefaultCompany.TrashAdventure",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Local Produce Tycoon",
        "project"       => "fusilli",
        "team"          => "21tiko3b",
        "team_name"     => "LTP",
        "description"   => "Play as a shopkeeper and with your choices take a step towards a greener future",
        "logo"          => "21tiko3b.webp",
        "website"       => "/21tiko3b/",
        "playstore"     => "https://play.google.com/store/apps/details?id=game.LPT.LocalProduceTycoon",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Laineilla",
        "project"       => "virma",
        "team"          => "21tiko2e",
        "team_name"     => "21tiko2e",
        "description"   => "Get passengers of steamship Tarjanne safely to their destination while avoiding obstacles.",
        "logo"          => "21tiko2e.webp",
        "website"       => "/21tiko2e/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.TIKO2E.Laineilla",
        "client"        => "Hopealinjat",
        "client_website"=> "https://www.hopealinjat.fi/en/",
    ],
    [
        "name"          => "Foodamid",
        "project"       => "fusilli",
        "team"          => "21tiko3d",
        "team_name"     => "T.A.J.R.O",
        "description"   => "Twist your thoughts in this challenging puzzle game! Learn about healthy food!",
        "logo"          => "21tiko3d.webp",
        "website"       => "/21tiko3d/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.T.A.J.R.O.Foodamid",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Polar Food Express",
        "project"       => "fusilli",
        "team"          => "21tiko3c",
        "team_name"     => "Team Pylly",
        "description"   => "A 2D endless runner game where you use a polar bear character to collect points and dodge obstacles.",
        "logo"          => "21tiko3c.webp",
        "website"       => "/21tiko3c/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.Pylly.PolarFoodExpress",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Fixin' Craze",
        "project"       => "virma",
        "team"          => "21tiko4e",
        "team_name"     => "Unikeko Games",
        "description"   => "Fix old cars back to their former glory!",
        "logo"          => "21tiko4e.webp",
        "website"       => "/21tiko4e/en_index.html",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.Tiko4E21.Game",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Kierrätysmania",
        "project"       => "ruoko",
        "team"          => "21tiko1c",
        "team_name"     => "21tiko1c",
        "description"   => "Fast-paced collection of recycling minigames",
        "logo"          => "21tiko1c.webp",
        "website"       => "/21tiko1c/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.tiko1c.Kierrtysmania",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Trashfarmer",
        "project"       => "ruoko",
        "team"          => "21tiko1d",
        "team_name"     => "21tiko1d",
        "description"   => "Your mission is to save the world by feeding certain types of trash to the right trash animals",
        "logo"          => "21tiko1d.webp",
        "website"       => "/21tiko1d/en/",
        "playstore"     => "https://play.google.com/store/apps/details?id=game.tiimi21tiko1d.Trashfarmer",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Villi yrttiseikkailu",
        "winner_place"  => 1,
        "project"       => "virma",
        "team"          => "21tiko2f",
        "team_name"     => "21tiko2f",
        "description"   => "Take on an adventure to your backyard and learn all about the edible greens in Finland!",
        "logo"          => "21tiko2f.webp",
        "website"       => "/21tiko2f/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.HortaGames.Villiyrttiseikkailu",
        "client"        => "Villipihlaja",
        "client_website"=> "https://www.villipihlaja.fi/?lang=en",
    ],
    [
        "name"          => "Museum Mayhem",
        "project"       => "virma",
        "team"          => "21tiko2c",
        "team_name"     => "Else False ",
        "description"   => "A mystery is brewing inside the Tampere Art Museum. Art is disappearing. Can you solve the mystery? ",
        "logo"          => "21tiko2c.webp",
        "website"       => "/21tiko2c/index_en.html",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.ElseFalse.MuseumMayhem",
        "client"        => "Tampere Art Museum",
        "client_website"=> "https://www.tampereentaidemuseo.fi/en/index.html  ",
    ],
    [
        "name"          => "Touhutalo",
        "project"       => "virma",
        "team"          => "21tiko4a",
        "team_name"     => "Ykkösryhmä",
        "description"   => "A set of five mini-games using the rooms of Mr. Clutterbuck's House as a base.",
        "logo"          => "21tiko4a.webp",
        "website"       => "/21tiko4a/",
        "playstore"     => null,
        "client"        => "The House of Mr. Clutterbuck",
        "client_website"=> "https://herrahakkaraisentalo.fi/in-english/",
    ],
    [
        "name"          => "Pocket Traveler",
        "project"       => "virma",
        "team"          => "21tiko2b",
        "team_name"     => null,
        "description"   => "Travel to two different countries with the app",
        "logo"          => "21tiko2b.webp",
        "website"       => "/21tiko2b/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.Tiko2B21.PocketTraveler",
        "client"        => "Virtuaalimatka.fi",
        "client_website"=> "https://virtuaalimatka.fi",
    ]
];

$config["games"]["fi"] = [  
    [
        "name"          => "Teatterin Mysteeri",
        "winner_place"  => 2,
        "project"       => "virma",
        "team"          => "21tiko4f",
        "team_name"     => "Rakettiryhmä",
        "description"   => "Tampereen Teatterin kummituslegenda on monelle tuttu, mutta sehän on vain vanhaa satua... vai onko?",
        "logo"          => "21tiko4f.webp",
        "website"       => "/21tiko4f/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.Rakettiryhm.TeatterinMysteeri",
        "appstore"      => "https://apps.apple.com/fi/app/teatterinmysteeri/id1623442275",
        "client"        => "Tampereen Teatteri",
        "client_website"=> "https://tampereenteatteri.fi/",
    ],
    [
        "name"          => "Rooftop Gardener",
        "project"       => "fusilli",
        "team"          => "21tiko3a",
        "team_name"     => "Team Chili",
        "description"   => "Get ready for fast-paced action protecting your rooftop garden!",
        "logo"          => "21tiko3a.webp",
        "website"       => "/21tiko3a/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.TeamChili.RooftopGardener",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Löylyn Taika",
        "project"       => "virma",
        "team"          => "21tiko2d",
        "team_name"     => "DEE",
        "description"   => "Saari, metsä, järvenranta ja saunatonttuoppilas. Tervetuloa taianomaiseen saunaan!",
        "logo"          => "21tiko2d.webp",
        "website"       => "/21tiko2d/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.TIKO2D.LylynTaika",
        "client"        => "Saunakonkeli",
        "client_website"=> "https://www.saunakonkeli.com/finnish",
    ],
    [
        "name"          => "Trash defender",
        "project"       => "ruoko",
        "team"          => "21tiko1a",
        "team_name"     => "NRE",
        "description"   => "Pelasta maailma roskilta Trash defender-pelissä!",
        "logo"          => "21tiko1a.webp",
        "website"       => "/21tiko1a/portaali.html",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.NRE.trash_defender",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Narwala",
        "project"       => "virma",
        "team"          => "21tiko4c",
        "team_name"     => "FragFrog",
        "description"   => "Kanasimulaattori. Pidä kanala siistinä, kasvata kanalasi kokoa ostamalla uusia kanoja ja osta kanoillesi hienoja hattuja!",
        "logo"          => "21tiko4c.webp",
        "website"       => "/21tiko4c/",
        "playstore"     => null,
        "client"        => "Narvan maatilamajoitus",
        "client_website"=> "https://www.narvanmaatilamajoitus.fi/",
    ],
    [
        "name"          => "SupperStar",
        "project"       => "fusilli",
        "team"          => "21tiko3e",
        "team_name"     => null,
        "description"   => "Tervetuloa paikalliseen SupperStar -ravintolaasi!",
        "logo"          => "21tiko3e.webp",
        "website"       => "/21tiko3e/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.Tiko3e.SupperStar",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Takeaway Hero",
        "project"       => "ruoko",
        "team"          => "21tiko1e",
        "team_name"     => null,
        "description"   => "Pakkaa ruuat, lajittele roskat, äläkä anna niiden joutua sekajätteisiin. Ole sankari! Kierrätä sinäkin!",
        "logo"          => "21tiko1e.webp",
        "website"       => "/21tiko1e/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.TIKO1E.TakeawayHero",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Ilola Express",
        "project"       => "virma",
        "team"          => "21tiko4d",
        "team_name"     => "J-A-L-O",
        "description"   => "Maatilateemainen versio pienillä muokkauksilla tunnetusta matopelistä.",
        "logo"          => "21tiko4d.webp",
        "website"       => "/21tiko4d/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.JALO.IlolaExpress",
        "client"        => "Ilolan maatila",
        "client_website"=> "https://www.ilolanmaatila.fi/",
    ],
    [
        "name"          => "Amazing Jump",
        "project"       => "virma",
        "team"          => "21tiko4b",
        "team_name"     => "KoodiÄijät",
        "description"   => "Peli on endless runner jossa rotta hyppii katolla ja sinun pitää väistää esteitä.",
        "logo"          => "21tiko4b.webp",
        "website"       => "/21tiko4b/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.Koodiijt.AmazingJump",
        "client"        => "Amazing City",
        "client_website"=> "https://amazingcity.fi/",
    ],
    [
        "name"          => "Trash Adventure",
        "project"       => "ruoko",
        "team"          => "21tiko1b",
        "team_name"     => null,
        "description"   => "Lajittele tiesi take-away -vihollisten valtaamien asuntojen läpi, ja lajittele roskasi!",
        "logo"          => "21tiko1b.webp",
        "website"       => "/21tiko1b/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.DefaultCompany.TrashAdventure",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Local Produce Tycoon",
        "project"       => "fusilli",
        "team"          => "21tiko3b",
        "team_name"     => null,
        "description"   => "Pelaa kauppiaana ja ota valinnoillasi askel kohti vihreämpää tulevaisuutta!",
        "logo"          => "21tiko3b.webp",
        "website"       => "/21tiko3b/",
        "playstore"     => "https://play.google.com/store/apps/details?id=game.LPT.LocalProduceTycoon",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Laineilla",
        "project"       => "virma",
        "team"          => "21tiko2e",
        "team_name"     => "21tiko2e",
        "description"   => "Kuljeta Tarjanne-höyrylaivan matkustajat turvallisesti perille esteitä väistellen.",
        "logo"          => "21tiko2e.webp",
        "website"       => "/21tiko2e/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.TIKO2E.Laineilla",
        "client"        => "Hopealinjat",
        "client_website"=> "https://www.hopealinjat.fi/",
    ],
    [
        "name"          => "Foodamid",
        "project"       => "fusilli",
        "team"          => "21tiko3d",
        "team_name"     => "T.A.J.R.O",
        "description"   => "Hauska peli, joka pistää ajatukset vinkkuraan samalla kun opit!",
        "logo"          => "21tiko3d.webp",
        "website"       => "/21tiko3d/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.T.A.J.R.O.Foodamid",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Polar Food Express",
        "project"       => "fusilli",
        "team"          => "21tiko3c",
        "team_name"     => "Team Pylly",
        "description"   => "2D endless runner peli, jossa jääkarhuhahmolla kerätään pisteitä ja väistellään esteitä.",
        "logo"          => "21tiko3c.webp",
        "website"       => "/21tiko3c/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.Pylly.PolarFoodExpress",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Fixin' Craze",
        "project"       => "virma",
        "team"          => "21tiko4e",
        "team_name"     => "Unikeko Games",
        "description"   => "Korjaa vanhat autot uuteen uskoon!",
        "logo"          => "21tiko4e.webp",
        "website"       => "/21tiko4e/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.Tiko4E21.Game",
        "client"        => "Vehoniemen Automuseo",
        "client_website"=> "https://automuseo.com/",
    ],
    [
        "name"          => "Kierrätysmania",
        "project"       => "ruoko",
        "team"          => "21tiko1c",
        "team_name"     => "21tiko1c",
        "description"   => "Nopeatempoinen kierrätysminipelien kokoelma",
        "logo"          => "21tiko1c.webp",
        "website"       => "/21tiko1c/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.tiko1c.Kierrtysmania",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Trashfarmer",
        "project"       => "ruoko",
        "team"          => "21tiko1d",
        "team_name"     => "21tiko1d",
        "description"   => "Tehtävänäsi on pelastaa maailma ruokkimalla tietyntyyppisiä roskia oikeille roskaeläimille.",
        "logo"          => "21tiko1d.webp",
        "website"       => "/21tiko1d/",
        "playstore"     => "https://play.google.com/store/apps/details?id=game.tiimi21tiko1d.Trashfarmer",
        "client"        => null,
        "client_website"=> null,
    ],
    [
        "name"          => "Villi yrttiseikkailu",
        "winner_place"  => 1,
        "project"       => "virma",
        "team"          => "21tiko2f",
        "team_name"     => "Horta Games",
        "description"   => "Lähde seikkailemaan takapihallesi ja tutustu Suomen luonnosta löytyviin syötäviin villiyrtteihin ja -vihanneksiin!",
        "logo"          => "21tiko2f.webp",
        "website"       => "/21tiko2f/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.HortaGames.Villiyrttiseikkailu",
        "client"        => "Villipihlaja",
        "client_website"=> "https://www.villipihlaja.fi/",
    ],
    [
        "name"          => "Museo Myllerryksessä",
        "project"       => "virma",
        "team"          => "21tiko2c",
        "team_name"     => "Else False ",
        "description"   => "Tampereen taidemuseolla tapahtuu kummia. Taidetta katoilee ja näyttely on kaaoksessa.",
        "logo"          => "21tiko2c.webp",
        "website"       => "/21tiko2c/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.ElseFalse.MuseumMayhem",
        "client"        => "Tampereen Taidemuseo",
        "client_website"=> "https://www.tampereentaidemuseo.fi/ ",
    ],
    [
        "name"          => "Touhutalo",
        "project"       => "virma",
        "team"          => "21tiko4a",
        "team_name"     => "Ykkösryhmä",
        "description"   => "Viidestä minipelistä koostuva kokonaisuus, joissa on käytetty Herra Hakkaraisen Talon huoneita pohjana.",
        "logo"          => "21tiko4a.webp",
        "website"       => "/21tiko4a/",
        "playstore"     => null,
        "client"        => "Herra Hakkaraisen Talo",
        "client_website"=> "https://herrahakkaraisentalo.fi/",
    ],
    [
        "name"          => "Pocket Traveler",
        "project"       => "virma",
        "team"          => "21tiko2b",
        "team_name"     => null,
        "description"   => "Meillä on mielenkiintoista tietoa ja temaattisesti sopiva fysiikkapohjainen peli jokaiselle maalle.",
        "logo"          => "21tiko2b.webp",
        "website"       => "/21tiko2b/",
        "playstore"     => "https://play.google.com/store/apps/details?id=com.Tiko2B21.PocketTraveler",
        "client"        => "Virtuaalimatka.fi",
        "client_website"=> "https://virtuaalimatka.fi",
    ]
];